project:
  type: website

website:
  title: "ESSB Repro Checks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - submit.qmd
      - workshops.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

